POINTS_MAPPING = {
    # National Initiatives
    "ncc": 60,
    "nss": 60,
    "ncc_c-certificate": 80,  # Additional points for NCC/NSS C-certificate
    "nptel": 20,
    "nptel + 8 week": 30,
    "nptel + 12 week": 50,
    # Sports & Games
    "sports participation": 8,
    "games participation": 8,
    "sports + 1st prize": 20,
    "sports + 2nd prize": 16,
    "sports + 3rd prize": 12,

    # Cultural Activities
    "music": 8,
    "performing arts": 8,
    "literary arts": 8,
    "cultural + 1st prize": 20,
    "cultural + 2nd prize": 16,
    "cultural + 3rd prize": 12,

    # Professional Self Initiatives
    "tech fest": 10,
    "tech quiz": 10,
    "Excel":15,
    "mooc": 50,
    "competitions + ieee": 40,
    "competitions + iet": 40,
    "conference + iit": 40,
    "conference + nit": 40,
    "paper presentation + iit": 40,
    "paper presentation + nit": 40,
    "industrial training": 20,
    "foreign language skill": 50,

    # Entrepreneurship & Innovation
    "startup company": 60,
    "patent filed": 30,
    "patent published": 35,
    "patent approved": 50,
    "patent licensed": 80,
    "prototype developed": 60,
    "venture capital funding": 80,
    "startup employment": 80,

    # Leadership & Management student societies
    "student society member": 10,
    "student society executive": 15,
    "festival coordinator": 15,
    "chairman": 15,
    "secretary": 15,
    #"chairperson":15,
    "Tech lead":15,
    "tech sub lead":15,
    "content lead":15,
    "Design lead":15,
    "Media lead":15,
    "Marketing lead":15,
    "Publicity lead":15,
    "Research lead":15,
    "AI/ML Lead":15,
    "Tech head":15,
    "tech sub head":15,
    "content head":15,
    "Design head":15,
    "Media head":15,
    "Marketing head":15,
    "Publicity head":15,
    "Research head":15,
    "AI/ML head":15,
    "Operations mangaer":15,
    "joint secretary":15,
    "Treasurer":15,
    "elected council member": 15,
    "general secretary":15,
    "Event head":15,
    "Initiatives head":15,
    "tech coordinator":15,
    "content coordinator":15,
    "Design coordinator":15,
    "Media coordinator":15,
    "Marketing coordinator":15,
    "Publicity coordinator":15,
    "Research coordinator":15,
    "BIDD incharge":15,
    "marketing head":15,
    "social media head":15,
    "PC documentaion":15,
    "documentation head":15,
    "embs representative":15,
    "echo and impulse heads":15,
    "design head":15,
    "content head":15,
    "secretary":15,
    "presdident":15,
    "community head":15,
    "reader's forum head":15,
    "tech head":15,
    "speaker's forum head":15,
    "writer's forum head":15,
    "vice president":15,
    #"chairperson":15,
    "operatives head":15,
    "general coordinators":15,
    "initiatives head":15,
    #"chairperson":15,
    "vice-chairperson":15,
    "web admin":15,
    "design head":15,
    "excecutive member":15,
    "CP lead":15,
    "Outreach lead":15,
    "finance head":15,
    "inclusivity lead":15,
    "tech sub lead":15,
    "web and project coordinator":15,
    "operations manager":15,
    "MDC":15,
    "TC":15,
    "RUHIRASENA LEADS":15,
    "NRPF LEADS":15,
    "KTU CARE LEADS":15,
    "ENERGY CELLS":15,
    "CAMPUS DIRECTOR":15,
    "DEPUTY CAMPUS DIRECTOR":15,
    "CAMPUS LEADS":15,
    "DEPUTY CAMPUS LEADS":15,
    "PHOTOGRAPHY & EDITING LEADS":15,
    "CHEIF TECHNOLOGY OFFICER":15,
    "CHEIF COMMUNITY OFFICER":15,
    "CHEIF PUBLICITY OFFICER":15,
    "CHEIF EXECUTIVE OFFICER":15,
    "CHIEF DESIGN OFFICER":15,
    "CHEIF EVENT MANAGEMENT OFFICER":15,
    "CHIEF PROJECT MANAGEMENT OFFICER":15,
    "CHIEF SOCIAL RESPONSIBLITY OFFICER":15,
    "CHEIF MARKETING OFFICER":15,
    "CHIEF SOCIAL MEDIA OFFICER":15,
    "CHIEF FINANCIAL OFFICER":15,
    "CHEIF OPERATING OFFICER":15,
    "CHEIF CONTENT OFFICER":15,
    "TALKS MANAGER":15,


    "volunteer secretary":15,
    "Campus lead":15,
    "documentation head":15,
    "documentation lead":15,
    }